# Generated by Django 4.2.11 on 2024-03-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseInfo', '0002_alter_elo_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tlo',
            name='code',
        ),
        migrations.AddField(
            model_name='tlo',
            name='key_words',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.RemoveField(
            model_name='course',
            name='elos',
        ),
        migrations.RemoveField(
            model_name='course',
            name='ptbs',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tlos',
        ),
        migrations.AddField(
            model_name='course',
            name='elos',
            field=models.ManyToManyField(related_name='%(class)s_elo', to='CourseInfo.elo'),
        ),
        migrations.AddField(
            model_name='course',
            name='ptbs',
            field=models.ManyToManyField(to='CourseInfo.ptb'),
        ),
        migrations.AddField(
            model_name='course',
            name='tlos',
            field=models.ManyToManyField(to='CourseInfo.tlo'),
        ),
    ]
