# Generated by Django 4.2.11 on 2024-03-15 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CourseInfo', '0004_alter_course_dhs_competencies_alter_course_elos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='dhs_competencies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CourseInfo.competency'),
        ),
        migrations.AlterField(
            model_name='course',
            name='elos',
            field=models.ManyToManyField(blank=True, null=True, related_name='%(class)s_elo', to='CourseInfo.elo'),
        ),
        migrations.AlterField(
            model_name='course',
            name='ptbs',
            field=models.ManyToManyField(blank=True, null=True, to='CourseInfo.ptb'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tlos',
            field=models.ManyToManyField(blank=True, null=True, to='CourseInfo.tlo'),
        ),
    ]
