# Generated by Django 4.2.11 on 2024-03-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseInfo', '0005_alter_course_dhs_competencies_alter_course_elos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elo',
            name='course',
        ),
        migrations.AlterField(
            model_name='course',
            name='elos',
            field=models.ManyToManyField(blank=True, null=True, to='CourseInfo.elo'),
        ),
    ]
