# Generated by Django 4.2.11 on 2024-03-17 15:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CourseInfo', '0006_remove_elo_course_alter_course_elos'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testfile', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])], verbose_name='Testbank spreadsheet')),
            ],
        ),
        migrations.RemoveField(
            model_name='module',
            name='elo',
        ),
        migrations.AddField(
            model_name='module',
            name='elos',
            field=models.ManyToManyField(to='CourseInfo.elo'),
        ),
        migrations.AlterField(
            model_name='course',
            name='elos',
            field=models.ManyToManyField(blank=True, to='CourseInfo.elo'),
        ),
        migrations.AlterField(
            model_name='course',
            name='ptbs',
            field=models.ManyToManyField(blank=True, to='CourseInfo.ptb'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tlos',
            field=models.ManyToManyField(blank=True, to='CourseInfo.tlo'),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CourseInfo.course'),
        ),
        migrations.AlterField(
            model_name='module',
            name='number_of_activities',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='number_of_slides',
            field=models.IntegerField(blank=True),
        ),
        migrations.RemoveField(
            model_name='module',
            name='tb_items',
        ),
        migrations.AddField(
            model_name='module',
            name='tb_items',
            field=models.ManyToManyField(to='CourseInfo.tbitem'),
        ),
    ]
