# Generated by Django 4.2.11 on 2024-03-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseInfo', '0007_file_remove_module_elo_module_elos_alter_course_elos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_title',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='module',
            name='module_number',
            field=models.CharField(max_length=50),
        ),
    ]
