# Generated by Django 4.2.11 on 2024-03-17 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CourseInfo', '0008_module_module_title_alter_module_module_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='elos',
            field=models.ManyToManyField(blank=True, to='CourseInfo.elo'),
        ),
        migrations.AlterField(
            model_name='module',
            name='tb_items',
            field=models.ManyToManyField(blank=True, to='CourseInfo.tbitem'),
        ),
        migrations.AlterField(
            model_name='module',
            name='tlo',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CourseInfo.tlo'),
        ),
    ]
