# Generated by Django 4.2.11 on 2024-03-17 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CourseInfo', '0009_alter_module_elos_alter_module_tb_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='tlo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CourseInfo.tlo'),
        ),
    ]
