# Generated by Django 4.2.11 on 2024-03-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseInfo', '0010_alter_module_tlo'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='ptbs',
            field=models.ManyToManyField(blank=True, to='CourseInfo.ptb'),
        ),
    ]
