# Generated by Django 4.2.11 on 2024-03-17 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseInfo', '0011_module_ptbs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='dhs_competencies',
        ),
        migrations.RemoveField(
            model_name='course',
            name='elos',
        ),
        migrations.RemoveField(
            model_name='course',
            name='ptbs',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tlos',
        ),
    ]
