# Generated by Django 4.2.11 on 2024-03-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseInfo', '0013_elo_key_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='competencies',
            field=models.ManyToManyField(blank=True, to='CourseInfo.competency'),
        ),
    ]
