# Generated by Django 4.2.11 on 2024-03-17 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseInfo', '0014_module_competencies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='minutes_to_complete',
        ),
        migrations.RemoveField(
            model_name='course',
            name='number_of_modules',
        ),
    ]
