# Generated by Django 4.2.11 on 2024-03-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseInfo', '0015_remove_course_minutes_to_complete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='tlo',
        ),
        migrations.AddField(
            model_name='module',
            name='tlo',
            field=models.ManyToManyField(blank=True, to='CourseInfo.tlo'),
        ),
    ]
