# Generated by Django 4.2.11 on 2024-03-18 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseInfo', '0016_remove_module_tlo_module_tlo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='tlo',
            new_name='tlos',
        ),
    ]
