# Generated by Django 4.2.11 on 2024-03-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseInfo', '0017_rename_tlo_module_tlos'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='dhs_comp',
            field=models.BooleanField(default=False),
        ),
    ]
